const jobs = [
  {
    id: 1,
    title: "Engineering Lead",
    company: "Frappe",
    type: "Full-time",
    location: "Mumbai",
    department: "Research & Development",
    salary: "₹21,00,000 - ₹30,00,000 / year",
    posted: "1 day ago",
    applications: 50,
    closing: "31 Oct, 2024",
  },
  {
    id: 2,
    title: "Designer",
    company: "Frappe",
    type: "Part-time",
    location: "Mumbai",
    department: "Research & Development",
    salary: "",
    posted: "1 week ago",
    applications: 20,
    closing: "31 Aug, 2024",
  },
  {
    id: 3,
    title: "Accountant",
    company: "Frappe",
    type: "Full-time",
    location: "Mumbai",
    department: "Accounts",
    salary: "",
    posted: "1 month ago",
    applications: 30,
    closing: "15 Aug, 2024",
  },
  {
    id: 4,
    title: "Engineer",
    company: "Frappe",
    type: "Full-time",
    location: "Mumbai",
    department: "Research & Development",
    salary: "",
    posted: "1 month ago",
    applications: 18,
    closing: "31 Jul, 2024",
  },
  {
    id: 5,
    title: "Head of Marketing and Sales",
    company: "Frappe",
    type: "Full-time",
    location: "New York",
    department: "Marketing",
    salary: "$50,000 - $80,000 / year",
    posted: "7 months ago",
    applications: 40,
    closing: "30 Sep, 2024",
  },
  {
    id: 6,
    title: "Marketer",
    company: "Frappe",
    type: "Intern",
    location: "Bangalore",
    department: "Marketing",
    salary: "",
    posted: "2 months ago",
    applications: 10,
    closing: "20 Aug, 2024",
  },
];

export default jobs;